module.exports = {
  parseVcard: function(vcardString) {
    var fields, result;
    fields = vcardString.split(/\r\n|\r|\n/);
    result = {};
    fields.forEach(function(field) {
      var parts;
      if (field.match(/^FN/)) {
        result.fn = field.split(':')[1];
      }
      if (parts = field.match(/^TEL\W(\w{1,})\W(.*)/i)) {
        if (result.tel == null) {
          result.tel = {};
        }
        return result.tel[parts[1]] = parts[2];
      }
    });
    return result;
  }
};

// ---
// generated by coffee-script 1.9.2